-- IPL Project Roles

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS IPL_ADMIN;
CREATE ROLE IF NOT EXISTS IPL_INGEST;
CREATE ROLE IF NOT EXISTS IPL_TRANSFORM;
CREATE ROLE IF NOT EXISTS IPL_REPORTING;
